# Generated by Django 4.2.21 on 2025-08-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('parrot', 'Parrot'), ('fish', 'Fish'), ('turtle', 'Turtle'), ('snake', 'Snake'), ('horse', 'Horse'), ('other', 'Other')], max_length=10),
        ),
    ]
