# Generated by Django 4.2.21 on 2025-08-29 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sender', 'receiver', 'pet', 'content')},
        ),
    ]
