# Generated by Django 4.2.21 on 2025-09-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_alter_message_options_alter_message_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-is_pinned', 'created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('birds', 'Birds'), ('fish', 'Fish'), ('turtle', 'Turtle'), ('snake', 'Snake'), ('horse', 'Horse'), ('other', 'Other')], max_length=10),
        ),
    ]
