# Generated by Django 4.2.21 on 2025-09-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_alter_message_options_message_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
    ]
