# Generated by Django 4.2.21 on 2025-09-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_alter_message_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='photo',
        ),
    ]
